name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
          key: deps-${{ hashFiles('deps.edn') }}
      - name: reuse lint
        run: nix develop --command reuse lint
      - name: bun install
        working-directory: web
        run: nix develop --command bun install --frozen-lockfile
      - name: compile
        run: nix develop --command clj -X:compile
